"""add new field for appointment

Revision ID: 070c11c834a3
Revises: 725581faf17e
Create Date: 2026-09-25 16:53:06.809341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '070c11c834a3'
down_revision = '725581faf17e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_appointment', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_booking', schema=None) as batch_op:
        batch_op.drop_column('is_appointment')

    # ### end Alembic commands ###
