"""Create new table expense head and referred

Revision ID: 09b76107790a
Revises: 83dda0884658
Create Date: 2025-09-02 17:12:06.270960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09b76107790a'
down_revision = '83dda0884658'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referred',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=225), nullable=False),
    sa.Column('contact_no', sa.String(length=50), nullable=True),
    sa.Column('is_doctor', sa.Boolean(), nullable=True),
    sa.Column('location', sa.String(length=225), nullable=False),
    sa.Column('specialization', sa.String(length=225), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('discount_to_patient', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('referred')
    # ### end Alembic commands ###
