"""Change in branch table

Revision ID: 0e99cb59dcaf
Revises: 690b0a2ec5e3
Create Date: 2025-09-13 01:53:21.046696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e99cb59dcaf'
down_revision = '690b0a2ec5e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('branch', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('additional_contact_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=225), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('branch', schema=None) as batch_op:
        batch_op.drop_column('address')
        batch_op.drop_column('additional_contact_number')
        batch_op.drop_column('contact_number')

    # ### end Alembic commands ###
