"""removeal  of give_share_to 

Revision ID: 10521cf33513
Revises: 93b597d2833f
Create Date: 2025-11-17 20:11:19.237203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10521cf33513'
down_revision = '93b597d2833f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_booking', schema=None) as batch_op:
        batch_op.drop_column('give_share_to')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('give_share_to', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
