"""adding of give_share_to

Revision ID: 13c31d963413
Revises: 10521cf33513
Create Date: 2025-11-17 20:34:31.993723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13c31d963413'
down_revision = '10521cf33513'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('give_share_to', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_booking', schema=None) as batch_op:
        batch_op.drop_column('give_share_to')

    # ### end Alembic commands ###
