"""Update report charges

Revision ID: 203e9d6402c4
Revises: 2af0148dc68f
Create Date: 2026-09-18 17:29:00.558250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '203e9d6402c4'
down_revision = '2af0148dc68f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor_category_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doctor_id', 'category', name='uq_doctor_category')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('doctor_category_rates')
    # ### end Alembic commands ###
