"""Add new field in test reg

Revision ID: 21e057b416e1
Revises: f3800ee2f0a6
Create Date: 2026-09-08 19:09:07.216796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21e057b416e1'
down_revision = 'f3800ee2f0a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_registration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_test_registration_category'), ['category'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_registration', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_registration_category'))
        batch_op.drop_column('category')

    # ### end Alembic commands ###
