"""Add new table Doctor report details

Revision ID: 24ff293a674c
Revises: 43eee9a9311d
Create Date: 2025-12-04 19:34:36.643641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24ff293a674c'
down_revision = '43eee9a9311d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor_report_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_name', sa.String(length=225), nullable=False),
    sa.Column('gender', sa.String(length=225), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('referred_doctor', sa.String(length=225), nullable=True),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.String(length=225), nullable=False),
    sa.Column('clinical_info', sa.Text(), nullable=True),
    sa.Column('scanning_protocols', sa.Text(), nullable=True),
    sa.Column('findings', sa.Text(), nullable=True),
    sa.Column('conclusion', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('doctor_reporting_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('report_details_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('doctor_signature', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('doctor_signature')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('doctor_reporting_details', schema=None) as batch_op:
        batch_op.drop_column('report_details_id')

    op.drop_table('doctor_report_data')
    # ### end Alembic commands ###
