"""Change in Test Booking for comments

Revision ID: 26ac78c51d8f
Revises: bbff20c69a7c
Create Date: 2025-09-19 14:58:49.618478

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '26ac78c51d8f'
down_revision = 'bbff20c69a7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('technician_comments', sa.JSON(), nullable=True))
        batch_op.drop_column('techician_comments')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('techician_comments', mysql.JSON(), nullable=True))
        batch_op.drop_column('technician_comments')

    # ### end Alembic commands ###
