"""Add file Feild in doctor reports

Revision ID: 297fdf77c3f7
Revises: 72316a328c2c
Create Date: 2026-05-14 21:13:58.602960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '297fdf77c3f7'
down_revision = '72316a328c2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor_report_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('report_file_url', sa.String(length=1024), nullable=True))
        batch_op.add_column(sa.Column('report_file_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('file_mime_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('file_size_bytes', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor_report_data', schema=None) as batch_op:
        batch_op.drop_column('file_size_bytes')
        batch_op.drop_column('file_mime_type')
        batch_op.drop_column('report_file_name')
        batch_op.drop_column('report_file_url')

    # ### end Alembic commands ###
