"""add new field

Revision ID: 2af0148dc68f
Revises: 21e057b416e1
Create Date: 2026-09-11 00:39:28.169449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2af0148dc68f'
down_revision = '21e057b416e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_booking', schema=None) as batch_op:
        batch_op.drop_column('total_amount')

    # ### end Alembic commands ###
