"""Changes In enum of transactions

Revision ID: 31b2ef39c683
Revises: 8e36bc64739f
Create Date: 2026-03-06 23:56:07.776747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31b2ef39c683'
down_revision = '8e36bc64739f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking_transfer_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('new_booking_id', sa.Integer(), nullable=True),
    sa.Column('old_booking_id', sa.Integer(), nullable=True),
    sa.Column('from_branch_id', sa.Integer(), nullable=False),
    sa.Column('to_branch_id', sa.Integer(), nullable=False),
    sa.Column('transferred_by_user_id', sa.Integer(), nullable=False),
    sa.Column('transferred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('patient_name', sa.String(length=225), nullable=True),
    sa.Column('mr_no', sa.String(length=225), nullable=True),
    sa.Column('transferred_cash_held', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['from_branch_id'], ['branch.id'], ),
    sa.ForeignKeyConstraint(['to_branch_id'], ['branch.id'], ),
    sa.ForeignKeyConstraint(['transferred_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    with op.batch_alter_table('test_booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_transferred_in', sa.Boolean(), nullable=True))

    # --- Manually added Enum update for payment_transactions ---
    with op.batch_alter_table('payment_transactions', schema=None) as batch_op:
        batch_op.alter_column(
            'transaction_type',
            existing_type=sa.Enum("Initial", "DueClearance", "Expense", name="trans_type"),
            type_=sa.Enum("Initial", "DueClearance", "Expense", "TransferOut_Held", name="trans_type"),
            existing_nullable=True
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # --- Manually added Enum revert for payment_transactions ---
    with op.batch_alter_table('payment_transactions', schema=None) as batch_op:
        batch_op.alter_column(
            'transaction_type',
            existing_type=sa.Enum("Initial", "DueClearance", "Expense", "TransferOut_Held", name="trans_type"),
            type_=sa.Enum("Initial", "DueClearance", "Expense", name="trans_type"),
            existing_nullable=True
        )

    with op.batch_alter_table('test_booking', schema=None) as batch_op:
        batch_op.drop_column('is_transferred_in')
 
    op.drop_table('booking_transfer_logs')
    # ### end Alembic commands ###