"""change in json to text

Revision ID: 338bd3f24f39
Revises: 26ac78c51d8f
Create Date: 2025-10-02 00:21:07.722241

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '338bd3f24f39'
down_revision = '26ac78c51d8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_booking', schema=None) as batch_op:
        batch_op.alter_column('technician_comments',
               existing_type=mysql.JSON(),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_booking', schema=None) as batch_op:
        batch_op.alter_column('technician_comments',
               existing_type=sa.Text(),
               type_=mysql.JSON(),
               existing_nullable=True)

    # ### end Alembic commands ###
