"""Update Test Registration

Revision ID: 3afff5b37025
Revises: c19077839c80
Create Date: 2025-12-29 18:29:29.405960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3afff5b37025'
down_revision = 'c19077839c80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_registration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('report_charges', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_registration', schema=None) as batch_op:
        batch_op.drop_column('report_charges')

    # ### end Alembic commands ###
