"""Expense Table added

Revision ID: 3ca396d0c14b
Revises: 338bd3f24f39
Create Date: 2025-10-08 23:49:21.576859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ca396d0c14b'
down_revision = '338bd3f24f39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Branch_id', sa.String(length=225), nullable=False),
    sa.Column('expense_head_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=225), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('ref_no', sa.String(length=50), nullable=True),
    sa.Column('payment_method', sa.Enum('Cash', 'Card', 'Online', 'Other', name='payment_enum'), nullable=True),
    sa.Column('paid_to', sa.String(length=225), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=225), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=225), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expenses')
    # ### end Alembic commands ###
