"""Adding new tables for films 

Revision ID: 3e6fb8bffad5
Revises: 13c31d963413
Create Date: 2025-11-20 19:12:06.535450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e6fb8bffad5'
down_revision = '13c31d963413'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('film_inventory_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_date', sa.DateTime(), nullable=True),
    sa.Column('transaction_type', sa.Enum('IN', 'OUT', 'ADJUST', name='trans_type_enum'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('handled_by', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['test_booking.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_film_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('films_required', sa.Integer(), nullable=True),
    sa.Column('films_used', sa.Integer(), nullable=False),
    sa.Column('last_edited_old_value', sa.Integer(), nullable=True),
    sa.Column('usage_type', sa.Enum('Normal', 'Extra', 'Repeat', 'Error', name='usage_type_enum'), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('used_by', sa.Integer(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('last_edited_by', sa.Integer(), nullable=True),
    sa.Column('last_edited_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['test_booking.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_film_usage')
    op.drop_table('film_inventory_transactions')
    # ### end Alembic commands ###
