"""Add new table doctor

Revision ID: 43eee9a9311d
Revises: 63dfd55459fc
Create Date: 2025-12-01 23:03:53.387471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43eee9a9311d'
down_revision = '63dfd55459fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor_reporting_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.String(length=225), nullable=False),
    sa.Column('doctor_id', sa.String(length=225), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('Pending', 'Reported', 'Declined', name='status_enum'), nullable=True),
    sa.Column('report_at', sa.DateTime(), nullable=True),
    sa.Column('assign_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('doctor_reporting_details')
    # ### end Alembic commands ###
