"""Change in Test bookings

Revision ID: 5628ce84fc30
Revises: ee0dff3ef0dd
Create Date: 2025-09-11 17:25:18.557222

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5628ce84fc30'
down_revision = 'ee0dff3ef0dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_name', sa.String(length=225), nullable=False))
        batch_op.add_column(sa.Column('contact_no', sa.String(length=15), nullable=False))
        batch_op.add_column(sa.Column('referred_dr', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('referred_non_dr', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('give_share_to', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_no_of_films', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_no_of_films_used', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reason_for_more_films', sa.String(length=225), nullable=True))
        batch_op.alter_column('gender',
               existing_type=mysql.VARCHAR(length=225),
               type_=sa.Enum('Male', 'Female', 'Other', name='gender_enum'),
               nullable=False)
        batch_op.alter_column('branch_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('discount_type',
               existing_type=mysql.VARCHAR(length=225),
               type_=sa.Enum('None', 'Amount', 'Percentage', name='discount_enum'),
               existing_nullable=True)
        batch_op.alter_column('discount_value',
               existing_type=mysql.DECIMAL(precision=10, scale=0),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('net_receivable',
               existing_type=mysql.DECIMAL(precision=10, scale=0),
               type_=sa.Numeric(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('payment_type',
               existing_type=mysql.VARCHAR(length=225),
               type_=sa.Enum('Cash', 'Card', 'Online', 'Other', name='payment_enum'),
               existing_nullable=True)
        batch_op.alter_column('paid_amount',
               existing_type=mysql.DECIMAL(precision=10, scale=0),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('due_amount',
               existing_type=mysql.DECIMAL(precision=10, scale=0),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('create_by',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.create_unique_constraint(None, ['mr_no'])
        batch_op.drop_column('panel_name')
        batch_op.drop_column('password')
        batch_op.drop_column('referred_dr_id')
        batch_op.drop_column('dob')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dob', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('referred_dr_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('password', mysql.VARCHAR(length=225), nullable=True))
        batch_op.add_column(sa.Column('panel_name', mysql.VARCHAR(length=225), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('create_by',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('due_amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.DECIMAL(precision=10, scale=0),
               existing_nullable=True)
        batch_op.alter_column('paid_amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.DECIMAL(precision=10, scale=0),
               existing_nullable=True)
        batch_op.alter_column('payment_type',
               existing_type=sa.Enum('Cash', 'Card', 'Online', 'Other', name='payment_enum'),
               type_=mysql.VARCHAR(length=225),
               existing_nullable=True)
        batch_op.alter_column('net_receivable',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.DECIMAL(precision=10, scale=0),
               nullable=True)
        batch_op.alter_column('discount_value',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.DECIMAL(precision=10, scale=0),
               existing_nullable=True)
        batch_op.alter_column('discount_type',
               existing_type=sa.Enum('None', 'Amount', 'Percentage', name='discount_enum'),
               type_=mysql.VARCHAR(length=225),
               existing_nullable=True)
        batch_op.alter_column('branch_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('gender',
               existing_type=sa.Enum('Male', 'Female', 'Other', name='gender_enum'),
               type_=mysql.VARCHAR(length=225),
               nullable=True)
        batch_op.drop_column('reason_for_more_films')
        batch_op.drop_column('total_no_of_films_used')
        batch_op.drop_column('total_no_of_films')
        batch_op.drop_column('give_share_to')
        batch_op.drop_column('referred_non_dr')
        batch_op.drop_column('referred_dr')
        batch_op.drop_column('contact_no')
        batch_op.drop_column('patient_name')

    # ### end Alembic commands ###
