"""Initial migration

Revision ID: 58bc1e5001e6
Revises: 
Create Date: 2025-08-06 17:00:07.888503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58bc1e5001e6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(length=225), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(length=225), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=225), nullable=False),
    sa.Column('email', sa.String(length=225), nullable=False),
    sa.Column('password', sa.String(length=225), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('test_booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mr_no', sa.String(length=225), nullable=True),
    sa.Column('panel_name', sa.String(length=225), nullable=True),
    sa.Column('password', sa.String(length=225), nullable=True),
    sa.Column('gender', sa.String(length=225), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('referred_dr_id', sa.Integer(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('create_by', sa.Integer(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('discount_type', sa.String(length=225), nullable=True),
    sa.Column('discount_value', sa.Numeric(), nullable=True),
    sa.Column('net_receivable', sa.Numeric(), nullable=True),
    sa.Column('payment_type', sa.String(length=225), nullable=True),
    sa.Column('paid_amount', sa.Numeric(), nullable=True),
    sa.Column('due_amount', sa.Numeric(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('update_by', sa.Integer(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.id'], ),
    sa.ForeignKeyConstraint(['create_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_booking_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('test_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('rate', sa.Numeric(), nullable=True),
    sa.Column('amount', sa.Numeric(), nullable=True),
    sa.Column('required_days', sa.Integer(), nullable=True),
    sa.Column('reporting_date', sa.Date(), nullable=True),
    sa.Column('sample_to_follow', sa.String(length=225), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['test_booking.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_booking_details')
    op.drop_table('test_booking')
    op.drop_table('user')
    op.drop_table('role')
    op.drop_table('branch')
    # ### end Alembic commands ###
