"""remove Forgrin Key and Unused Col

Revision ID: 63dfd55459fc
Revises: 3e6fb8bffad5
Create Date: 2025-11-21 01:48:24.978058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63dfd55459fc'
down_revision = '3e6fb8bffad5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('film_inventory_transactions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('film_inventory_transactions_booking_id_fkey'), type_='foreignkey')

    with op.batch_alter_table('test_booking', schema=None) as batch_op:
        batch_op.drop_column('total_no_of_films')
        batch_op.drop_column('reason_for_more_films')

    with op.batch_alter_table('test_film_usage', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('test_film_usage_booking_id_fkey'), type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_film_usage', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('test_film_usage_booking_id_fkey'), 'test_booking', ['booking_id'], ['id'])

    with op.batch_alter_table('test_booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reason_for_more_films', sa.VARCHAR(length=225), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('total_no_of_films', sa.INTEGER(), autoincrement=False, nullable=True))

    with op.batch_alter_table('film_inventory_transactions', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('film_inventory_transactions_booking_id_fkey'), 'test_booking', ['booking_id'], ['id'])

    # ### end Alembic commands ###
