"""Change in Test bookings and details 

Revision ID: 690b0a2ec5e3
Revises: 5628ce84fc30
Create Date: 2025-09-11 18:22:02.023550

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '690b0a2ec5e3'
down_revision = '5628ce84fc30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_booking_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('no_of_films', sa.Integer(), nullable=True))
        batch_op.alter_column('booking_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('test_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('amount',
               existing_type=mysql.DECIMAL(precision=10, scale=0),
               type_=sa.Numeric(precision=10, scale=2),
               nullable=False)
        batch_op.drop_column('rate')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_booking_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rate', mysql.DECIMAL(precision=10, scale=0), nullable=True))
        batch_op.alter_column('amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.DECIMAL(precision=10, scale=0),
               nullable=True)
        batch_op.alter_column('test_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('booking_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_column('no_of_films')

    # ### end Alembic commands ###
