"""adding incidental_findings

Revision ID: 8130842c6880
Revises: 3afff5b37025
Create Date: 2026-01-20 17:35:27.774224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8130842c6880'
down_revision = '3afff5b37025'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor_report_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('incidental_findings', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor_report_data', schema=None) as batch_op:
        batch_op.drop_column('incidental_findings')

    # ### end Alembic commands ###
