"""add issue films at test details

Revision ID: 8b02591148d5
Revises: bf6ec920c63c
Create Date: 2025-12-19 01:27:38.744579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b02591148d5'
down_revision = 'bf6ec920c63c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_booking_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('film_issued', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_booking_details', schema=None) as batch_op:
        batch_op.drop_column('film_issued')

    # ### end Alembic commands ###
