"""initial_migration

Revision ID: 93b597d2833f
Revises: 
Create Date: 2025-11-17 17:30:09.869415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93b597d2833f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_name', sa.String(length=225), nullable=False),
    sa.Column('contact_number', sa.String(length=50), nullable=True),
    sa.Column('additional_contact_number', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=225), nullable=True),
    sa.Column('description', sa.String(length=225), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=225), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=225), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=225), nullable=False),
    sa.Column('description', sa.String(length=225), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=225), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=225), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expense_head',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=225), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('expense_head_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=225), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('ref_no', sa.String(length=50), nullable=True),
    sa.Column('payment_method', sa.Enum('Cash', 'Card', 'Online', 'Other', name='payment_enum'), nullable=True),
    sa.Column('paid_to', sa.String(length=225), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('referred',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=225), nullable=False),
    sa.Column('contact_no', sa.String(length=50), nullable=True),
    sa.Column('is_doctor', sa.Boolean(), nullable=True),
    sa.Column('location', sa.String(length=225), nullable=False),
    sa.Column('specialization', sa.String(length=225), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('discount_to_patient', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=225), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mr_no', sa.String(length=225), nullable=True),
    sa.Column('patient_name', sa.String(length=225), nullable=False),
    sa.Column('gender', sa.Enum('Male', 'Female', 'Other', name='gender_enum'), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('contact_no', sa.String(length=15), nullable=False),
    sa.Column('technician_comments', sa.Text(), nullable=True),
    sa.Column('referred_dr', sa.Integer(), nullable=True),
    sa.Column('referred_non_dr', sa.Integer(), nullable=True),
    sa.Column('give_share_to', sa.Integer(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('total_no_of_films', sa.Integer(), nullable=True),
    sa.Column('total_no_of_films_used', sa.Integer(), nullable=True),
    sa.Column('reason_for_more_films', sa.String(length=225), nullable=True),
    sa.Column('discount_type', sa.Enum('None', 'Amount', 'Percentage', name='discount_enum'), nullable=True),
    sa.Column('discount_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('net_receivable', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_type', sa.Enum('Cash', 'Card', 'Online', 'Other', name='payment_enum'), nullable=True),
    sa.Column('paid_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('due_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('create_by', sa.Integer(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('update_by', sa.Integer(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mr_no')
    )
    op.create_table('test_booking_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('no_of_films', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('required_days', sa.Integer(), nullable=True),
    sa.Column('reporting_date', sa.Date(), nullable=True),
    sa.Column('sample_to_follow', sa.String(length=225), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_registration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_name', sa.String(length=225), nullable=False),
    sa.Column('sample_collection', sa.String(length=50), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('charges', sa.Float(), nullable=False),
    sa.Column('required_days', sa.String(length=225), nullable=False),
    sa.Column('sequence_no', sa.String(length=225), nullable=True),
    sa.Column('no_of_films', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=225), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=225), nullable=False),
    sa.Column('email', sa.String(length=225), nullable=False),
    sa.Column('password', sa.String(length=225), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('test_registration')
    op.drop_table('test_booking_details')
    op.drop_table('test_booking')
    op.drop_table('role')
    op.drop_table('referred')
    op.drop_table('expenses')
    op.drop_table('expense_head')
    op.drop_table('department')
    op.drop_table('branch')
    # ### end Alembic commands ###
