"""Relation ship remove

Revision ID: 9bbfa12d5344
Revises: 58bc1e5001e6
Create Date: 2025-08-07 22:07:48.932298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bbfa12d5344'
down_revision = '58bc1e5001e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_booking', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('test_booking_ibfk_2'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('test_booking_ibfk_1'), type_='foreignkey')

    with op.batch_alter_table('test_booking_details', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('test_booking_details_ibfk_1'), type_='foreignkey')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('user_ibfk_2'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('user_ibfk_1'), type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('user_ibfk_1'), 'branch', ['branch_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('user_ibfk_2'), 'role', ['role_id'], ['id'])

    with op.batch_alter_table('test_booking_details', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('test_booking_details_ibfk_1'), 'test_booking', ['booking_id'], ['id'])

    with op.batch_alter_table('test_booking', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('test_booking_ibfk_1'), 'branch', ['branch_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('test_booking_ibfk_2'), 'user', ['create_by'], ['id'])

    # ### end Alembic commands ###
