"""Change in Test Booking for comments

Revision ID: bbff20c69a7c
Revises: 0e99cb59dcaf
Create Date: 2025-09-19 13:49:13.695861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbff20c69a7c'
down_revision = '0e99cb59dcaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('techician_comments', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_booking', schema=None) as batch_op:
        batch_op.drop_column('techician_comments')

    # ### end Alembic commands ###
