"""add new col in Doctorreporting details

Revision ID: bf6ec920c63c
Revises: 24ff293a674c
Create Date: 2025-12-09 14:57:02.562034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf6ec920c63c'
down_revision = '24ff293a674c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor_reporting_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor_reporting_details', schema=None) as batch_op:
        batch_op.drop_column('test_id')

    # ### end Alembic commands ###
