"""initial tables

Revision ID: c19077839c80
Revises: cc5ac8652954
Create Date: 2025-12-26 14:49:38.461554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c19077839c80'
down_revision = 'cc5ac8652954'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referral_share',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('referred_id', sa.Integer(), nullable=False),
    sa.Column('share_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('expense_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('referral_share', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_referral_share_booking_id'), ['booking_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('referral_share', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_referral_share_booking_id'))

    op.drop_table('referral_share')
    # ### end Alembic commands ###
