"""add tranction table

Revision ID: cc5ac8652954
Revises: 8b02591148d5
Create Date: 2025-12-22 02:14:02.477047

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql # <--- IMPORTANT NEW IMPORT

# revision identifiers, used by Alembic.
revision = 'cc5ac8652954'
down_revision = '8b02591148d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('expense_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    
    # New Enum: Let it create this one (direction_enum)
    sa.Column('direction', sa.Enum('IN', 'OUT', name='direction_enum'), nullable=False),
    
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    
    # FIX: Use postgresql.ENUM with create_type=False
    sa.Column('payment_type', postgresql.ENUM('Cash', 'Card', 'Online', 'Other', name='payment_enum', create_type=False), nullable=True),
    
    # New Enum: Let it create this one (trans_type)
    sa.Column('transaction_type', sa.Enum('Initial', 'DueClearance', 'Expense', name='trans_type'), nullable=True),
    
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    
    with op.batch_alter_table('payment_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_transactions_booking_id'), ['booking_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_transactions_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_transactions_expense_id'), ['expense_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_transactions_payment_date'), ['payment_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_transactions_payment_date'))
        batch_op.drop_index(batch_op.f('ix_payment_transactions_expense_id'))
        batch_op.drop_index(batch_op.f('ix_payment_transactions_branch_id'))
        batch_op.drop_index(batch_op.f('ix_payment_transactions_booking_id'))

    op.drop_table('payment_transactions')
    
    # Cleanup new enums on downgrade (optional)
    # We do NOT drop payment_enum because other tables use it
    op.execute("DROP TYPE IF EXISTS direction_enum")
    op.execute("DROP TYPE IF EXISTS trans_type")
    # ### end Alembic commands ###