"""Update age thing

Revision ID: e278d1f65ab2
Revises: 203e9d6402c4
Create Date: 2026-09-20 16:23:22.172344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e278d1f65ab2'
down_revision = '203e9d6402c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age_unit', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_booking', schema=None) as batch_op:
        batch_op.drop_column('age_unit')

    # ### end Alembic commands ###
