"""adding new table technician_chat_log

Revision ID: f3800ee2f0a6
Revises: c07d4f04f3a3
Create Date: 2026-06-12 13:57:51.092994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3800ee2f0a6'
down_revision = 'c07d4f04f3a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('technician_chat_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['test_booking.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('technician_chat_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_technician_chat_log_booking_id'), ['booking_id'], unique=False)

    with op.batch_alter_table('technician_booking_media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chat_log_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'technician_chat_log', ['chat_log_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('technician_booking_media', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('chat_log_id')

    with op.batch_alter_table('technician_chat_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_technician_chat_log_booking_id'))

    op.drop_table('technician_chat_log')
    # ### end Alembic commands ###
