"""Create department and test registration

Revision ID: fd8369603879
Revises: 09b76107790a
Create Date: 2025-09-03 13:03:13.586909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd8369603879'
down_revision = '09b76107790a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_name', sa.String(length=225), nullable=False),
    sa.Column('description', sa.String(length=225), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=225), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=225), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_registration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_name', sa.String(length=225), nullable=False),
    sa.Column('sample_collection', sa.String(length=50), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('charges', sa.Float(), nullable=False),
    sa.Column('required_days', sa.String(length=225), nullable=False),
    sa.Column('sequence_no', sa.String(length=225), nullable=False),
    sa.Column('no_of_films', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=225), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_registration')
    op.drop_table('Department')
    # ### end Alembic commands ###
