name: Deploy to On-Premise Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Pull Latest Changes and Rebuild Container
        run: |
          cd /home/tmcpos/tmc-pos
          git pull origin main
          docker compose up -d --build
          
          # Give the container 5 seconds to boot
          sleep 5
          
          # Force the running container to upgrade the database schema
          docker exec tmc_pos_container flask db upgrade